update

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -7,9 +7,11 @@ on:
       - github-ci
 
 jobs:
+
   ############################################
   #            Build                         #
   ############################################
+
   build_docker:
     runs-on: ubuntu-20.04
     steps:
@@ -31,9 +33,11 @@ jobs:
         with:
           path: fuzzware_latest.tar
           key: ${{ runner.os }}-dockerbuild
+
   ############################################
   #            Fuzzing                       #
   ############################################
+
   fuzzing_ARCH_PRO_docker:
     runs-on: ubuntu-20.04
     needs: build_docker
@@ -76,6 +80,10 @@ jobs:
           path: examples/P2IM/CNC/fuzzware-project-docker
           key: ${{ runner.os }}-cnc
 
+  ############################################
+  #            Commands                      #
+  ############################################
+
   fuzzware_cov_main_arch_pro_docker:
     runs-on: ubuntu-20.04
     needs: fuzzing_ARCH_PRO_docker
@@ -94,9 +102,6 @@ jobs:
         run: docker load -i fuzzware_latest.tar
       - run: ./run_docker.sh --no-tty ./examples/pw-recovery/ARCH_PRO/fuzzware-project-docker fuzzware cov main
 
-  ############################################
-  #            Commands                      #
-  ############################################
   fuzzware_emu_docker:
     runs-on: ubuntu-20.04
     needs: fuzzing_ARCH_PRO_docker
@@ -133,7 +138,6 @@ jobs:
         run: docker load -i fuzzware_latest.tar
       - run: ./run_docker.sh --no-tty ./examples/pw-recovery/ARCH_PRO/fuzzware-project-docker/ fuzzware replay --covering main -v
 
-
   fuzzware_gentraces_docker:
     runs-on: ubuntu-20.04
     needs: fuzzing_ARCH_PRO_docker
@@ -169,7 +173,119 @@ jobs:
       - name: load fuzzware image
         run: docker load -i fuzzware_latest.tar
       - run: ./run_docker.sh --no-tty ./examples/P2IM/CNC/fuzzware-project-docker fuzzware gentraces --dryrun
+
   ############################################
   #            Self-Contained                #
   ############################################
 
+  fuzzware_cov_self_contained_docker:
+    runs-on: ubuntu-20.04
+    needs: fuzzing_ARCH_PRO_docker
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3.0.0
+      - uses: actions/cache@v3
+        with:
+          path: fuzzware_latest.tar
+          key: ${{ runner.os }}-dockerbuild
+      - uses: actions/cache@v3
+        with:
+          path: examples/pw-recovery/ARCH_PRO/fuzzware-project-docker
+          key: ${{ runner.os }}-arch-pro
+      - name: load fuzzware image
+        run: docker load -i fuzzware_latest.tar
+      - name: Move project directory
+        run: mv examples/pw-recovery/ARCH_PRO/fuzzware-project-docker/ ./still_replayable_ARCH_PRO_docker
+      - run: ./run_docker.sh --no-tty ./still_replayable_ARCH_PRO_docker fuzzware gentraces --dryrun
+
+  fuzzware_replay_self_contained_docker:
+    runs-on: ubuntu-20.04
+    needs: fuzzing_ARCH_PRO_docker
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3.0.0
+      - uses: actions/cache@v3
+        with:
+          path: fuzzware_latest.tar
+          key: ${{ runner.os }}-dockerbuild
+      - uses: actions/cache@v3
+        with:
+          path: examples/pw-recovery/ARCH_PRO/fuzzware-project-docker
+          key: ${{ runner.os }}-arch-pro
+      - name: load fuzzware image
+        run: docker load -i fuzzware_latest.tar
+      - name: Move project directory
+        run: mv examples/pw-recovery/ARCH_PRO/fuzzware-project-docker/ ./still_replayable_ARCH_PRO_docker
+      - run: ./run_docker.sh --no-tty ./still_replayable_ARCH_PRO_docker fuzzware replay --covering main -v
+
+  fuzzware_gentraces_self_contained_docker:
+    runs-on: ubuntu-20.04
+    needs: fuzzing_ARCH_PRO_docker
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3.0.0
+      - uses: actions/cache@v3
+        with:
+          path: fuzzware_latest.tar
+          key: ${{ runner.os }}-dockerbuild
+      - uses: actions/cache@v3
+        with:
+          path: examples/pw-recovery/ARCH_PRO/fuzzware-project-docker
+          key: ${{ runner.os }}-arch-pro
+      - name: load fuzzware image
+        run: docker load -i fuzzware_latest.tar
+      - name: Move project directory
+        run: mv examples/pw-recovery/ARCH_PRO/fuzzware-project-docker/ ./still_replayable_ARCH_PRO_docker
+      - run: ./run_docker.sh --no-tty ./still_replayable_ARCH_PRO_docker fuzzware gentraces --dryrun
+
+  fuzzware_emu_self_contained_docker:
+    runs-on: ubuntu-20.04
+    needs: fuzzing_CNC_docker
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3.0.0
+      - uses: actions/cache@v3
+        with:
+          path: fuzzware_latest.tar
+          key: ${{ runner.os }}-dockerbuild
+      - uses: actions/cache@v3
+        with:
+          path: examples/P2IM/CNC/fuzzware-project-docker
+          key: ${{ runner.os }}-cnc
+      - name: load fuzzware image
+        run: docker load -i fuzzware_latest.tar
+      - name: Move project directory
+        run: mv examples/P2IM/CNC/fuzzware-project-docker/ ./still_replayable_CNC_docker
+      - run: ./run_docker.sh --no-tty ./still_replayable_CNC_docker fuzzware emu data/CNC.elf --config data/config.yml -v
+
+  fuzzware_genstats_self_contained_CNC_docker:
+    runs-on: ubuntu-20.04
+    needs: fuzzing_CNC_docker
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3.0.0
+      - uses: actions/cache@v3
+        with:
+          path: fuzzware_latest.tar
+          key: ${{ runner.os }}-dockerbuild
+      - uses: actions/cache@v3
+        with:
+          path: examples/P2IM/CNC/fuzzware-project-docker
+          key: ${{ runner.os }}-cnc
+      - name: load fuzzware image
+        run: docker load -i fuzzware_latest.tar
+      - name: Move project directory
+        run: mv examples/P2IM/CNC/fuzzware-project-docker/ ./still_replayable_CNC_docker
+      - name: run genstats
+        run: ./run_docker.sh --no-tty ./still_replayable_CNC_docker fuzzware genstats
+      - name: Check if output files were created
+        run: |
+            FILE1=./still_replayable_CNC_docker/stats/covered_bbs_by_second_into_experiment.csv
+            FILE2=./still_replayable_CNC_docker/stats/job_timing_summary.csv
+            if [[ -f "$FILE1"  && -f "$FILE2" ]]
+            then
+                echo "Output files were created!"
+                exit 0
+            fi
+            echo "Output files missing!"
+            exit 1
